pages: []
30Gk:
    - from: docs/Onboarding/
      to: versioned_docs/version-30Gk/Onboarding
    - from: docs/OF-BYOD-Basics-29/
      to: versioned_docs/version-30Gk/01-BYOD-Basics-29
      ignore:
          - 00-Szenarien.mdx
    - from: docs/OF-Programmieren-1/
      to: versioned_docs/version-30Gk/02-Programmieren-1
      ignore:
          - 50-Test
          - 51-Tests.mdx

